// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_azFedFsKdSCZ38FhwFjKX8uz2xo9afU',
    appId: '1:992790358390:web:25f39eee6c041485d73257',
    messagingSenderId: '992790358390',
    projectId: 'portifolio-7af8a',
    authDomain: 'portifolio-7af8a.firebaseapp.com',
    databaseURL: 'https://portifolio-7af8a-default-rtdb.firebaseio.com',
    storageBucket: 'portifolio-7af8a.firebasestorage.app',
    measurementId: 'G-653T5NK3GR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChPwbNX4Vp_MwASEDc8cNIo5VXsI1VAPo',
    appId: '1:992790358390:android:d5b1cdfd57d1c211d73257',
    messagingSenderId: '992790358390',
    projectId: 'portifolio-7af8a',
    databaseURL: 'https://portifolio-7af8a-default-rtdb.firebaseio.com',
    storageBucket: 'portifolio-7af8a.firebasestorage.app',
  );
}
